//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom;
using System.Collections.Generic;
using System.Data.Entity;

namespace DataAccess.Models
{
    public class Costumer
    {
 //    public Costumer()
 //       {
  ////          this.Costumers = new HashSet<Costumer>();   
     //   }   
        public string FirstName { set; get; }
        public string LastName { set; get; }
        public string SSN { set; get; }
        public string Email { set; get; }
        public string Phone { set; get; }
        public string UserName { set; get; }
        public int Password { set; get; }
        public double AccountBalacne { set; get; }

      //  public virtual ICollection<Costumer> Costumers { set; get; }
    }
}