//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Data.Entity;
using System.IO;

namespace DataAccess.Models
{
    public class Employee
    {
        //    public Employee()
        //     {
        //         this.Employees = new HashSet<Employee>();
        //      }
        public string FirstName { set; get; }
        public string LastName { set; get; }
        public string PersonalID { set; get; }
        public string UserName { set; get; }
        public string Email { set; get; }
        public string Password { set; get; }

        //  public virtual ICollection<Employee> Employees { set; get; }
    }
}