//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Net.NetworkInformation;

namespace DataAccess.Models
{
    public enum Package_Type
    {
        Object,
        Document,
        Breakable
    }
    public enum Post_Type
    {
        Ordinary,
        Leading
    }
    public enum Shipping_Status
    {
        Registered,
        ReadyToSend,
        Posted,
        Delivered
    }
    public class Order
    {
      //  public Order()
      //  {
       //     this.Orders = new HashSet<Order>();
 ///       }
        public string SenderAddress { get; set; }
        public string ReceiverAddress { get; set; }
        public Package_Type PackageType { get; set; }
        public double Weight { get; set; }
        public Post_Type PostType { get; set; }
        public string Phone { set; get; }
        public string CostumerSSN { get; set; }
        public int OrderID { get; set; }
        public Shipping_Status Shipping_Status { get; set; }
        public string Comment { get; set; }
       // public virtual ICollection<Order> Orders { get; set; }
    }
}